Estabelecimento/Controllers/GerenciadorController.cs
using Estabelecimento.Helpers;
using Estabelecimento.Modelo;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;


namespace Estabelecimento.Controllers
{
    public class GerenciadorController : Controller
    {
        string cnx = Properties.Settings.Default.str_cnx;

        public ActionResult Index(int categoria)
        {
            List<clsEstabelecimento> estabelecimentos = new List<clsEstabelecimento>();


            using(Contexto c = new Contexto(cnx))
            {
                estabelecimentos = (from e in
                   c.ExecuteQuery<clsEstabelecimento>("select * from [dbo].[Estabelecimento] where id_categoria =" + categoria).AsEnumerable()

                                    select new clsEstabelecimento
                                    {
                                        id_estabelecimento = e.id_estabelecimento,
                                        razao_social = e.razao_social,
                                        nome_fantasia = e.nome_fantasia,
                                        cnpj = e.cnpj,
                                        email = e.email,
                                        endereco = e.endereco,
                                        id_cidade = e.id_cidade,
                                        id_estado = e.id_estado,
                                        id_categoria = e.id_categoria,

                                        telefone = e.telefone,
                                        data_cadastro = e.data_cadastro,

                                        status = e.status,
                                        agencia = e.agencia,
                                        conta = e.conta,

                                        cidade = (
                                                        from cid in (c.ExecuteQuery<clsCidade>("select * from [dbo].[Cidade] where id_cidade =" +"'"+ e.id_cidade + "'" ).ToList())

                                                        select new clsCidade
                                                        {
                                                            id_cidade = cid.id_cidade,
                                                            nome_municipio = cid.nome_municipio
                                                        }

                                            ).FirstOrDefault(),

                                        estado = (
                                                        from est in (c.ExecuteQuery<clsEstado>("select * from [dbo].[Estado] where id_estado =" + "'" + e.id_estado + "'" ).ToList())

                                                        select new clsEstado
                                                        {
                                                            id_estado = est.id_estado,
                                                            nome = est.nome
                                                        }

                                            ).FirstOrDefault(),

                                        categoria = (
                                                        from cat in (c.ExecuteQuery<clsCategoria>("select * from [dbo].[Categoria] where id_categoria =" + "'" + e.id_categoria + "'").ToList())

                                                        select new clsCategoria
                                                        {
                                                            id_categoria = cat.id_categoria,
                                                            categoria = cat.categoria
                                                        }

                                            ).FirstOrDefault()

                                    }

                ).OrderBy(x => x.razao_social).ToList();

            }
            
            return View(estabelecimentos);
        }


        public PartialViewResult Editar(int id)
        {
            clsEstabelecimento estabelecimento = new clsEstabelecimento();
            List<clsCategoria> categorias = new List<clsCategoria>();
            List<clsEstado> estados = new List<clsEstado>();
            List<clsCidade> cidades = new List<clsCidade>();

            using (Contexto c = new Contexto(cnx))
            {
                estabelecimento = c.ExecuteQuery<clsEstabelecimento>("select * from [dbo].[Estabelecimento] where id_estabelecimento =" + id).FirstOrDefault();
                categorias = c.ExecuteQuery<clsCategoria>("select * from [dbo].[Categoria]").ToList();
                estados = c.ExecuteQuery<clsEstado>("select * from dbo.Estado").ToList();
                cidades = c.ExecuteQuery<clsCidade>("select * from [dbo].[Cidade]").ToList();

                c.Connection.Close();
                c.Connection.Dispose();
            }

            ViewBag.Categorias = categorias;
            ViewBag.Estados = estados;
            ViewBag.Cidades = cidades;


            return PartialView(estabelecimento);
        }


        [HttpPost]
        public JsonResult Editar(clsEstabelecimento estabelecimento)
        {
            retornoJson ret = new retornoJson();
            int retorno;

            //Validações
            if (string.IsNullOrWhiteSpace(estabelecimento.razao_social))
                ret.Mensagem += "Razão Social é um campo obrigatorio <br/>";

            if (string.IsNullOrWhiteSpace(estabelecimento.cnpj))
                ret.Mensagem += "CNPJ é um campo obrigatorio <br/>";

            if (estabelecimento.id_categoria == 0)
                ret.Mensagem += "Selecione a categoria <br/>";

            if (estabelecimento.id_categoria == 1)
            {
                if (string.IsNullOrWhiteSpace(estabelecimento.telefone))
                    ret.Mensagem += "Para a categoria SUPERMERCADO o telefone passa a ser obrigatorio. <br/>";
            }

            if (!string.IsNullOrWhiteSpace(estabelecimento.email))
            {
                if (Funcoes.IsEmail(estabelecimento.email) != true)
                    ret.Mensagem += "Formato de e-mail invalido. Use um e-mail valido. ex: meuEmail@meuServidor.com <br/>";

            }

            if (ret.Mensagem != null && ret.Mensagem != "")
                return Json(ret, JsonRequestBehavior.AllowGet);

            using (Contexto c = new Contexto(cnx))
            {
              retorno =  c.ExecuteCommand("[dbo].[estabelecimento_editar] {0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10},{11},{12}",
                                estabelecimento.id_estabelecimento, /*obrigatorio*/
                                estabelecimento.razao_social, /*obrigatorio*/
                                string.IsNullOrWhiteSpace(estabelecimento.nome_fantasia) ? "" : estabelecimento.nome_fantasia,
                                estabelecimento.cnpj, /*obrigatorio*/
                                string.IsNullOrWhiteSpace(estabelecimento.email) ? "" : estabelecimento.email,
                                string.IsNullOrWhiteSpace(estabelecimento.endereco) ? "" : estabelecimento.endereco,
                                estabelecimento.id_cidade ,
                                estabelecimento.id_estado ,
                                string.IsNullOrWhiteSpace(estabelecimento.telefone) ? "" : estabelecimento.telefone,
                                estabelecimento.id_categoria, /*obrigatorio*/
                                estabelecimento.status ,
                                string.IsNullOrWhiteSpace(estabelecimento.agencia) ? "" : estabelecimento.agencia,
                                string.IsNullOrWhiteSpace(estabelecimento.conta) ? "" : estabelecimento.conta
                            );

                c.Connection.Close();
                c.Connection.Dispose();
            }

            if (retorno == -1)
            {
                ret.Mensagem = "Este CNPJ ou este E-mail já esta cadastrado";
                ret.sucesso = false;
            }
            else if (retorno > 0)
            {
                ret.Mensagem = "Cadastrado com sucesso";
                ret.sucesso = true;
            }
            else
            {
                ret.Mensagem = "Não foi possivel realizar o cadastro";
                ret.sucesso = false;
            }

            return Json(ret, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult Excluir(int id_estabelecimento)
        {
            retornoJson ret = new retornoJson();
            int retorno;

            using(Contexto c = new Contexto(cnx))
            {
                retorno = c.ExecuteCommand("delete from [dbo].[Estabelecimento] where id_estabelecimento ="+ id_estabelecimento);
            }

            if(retorno == 1)
            {
                ret.Mensagem = "Estabelecimento excluido";
                ret.sucesso = true;
            }else
            {
                ret.Mensagem = "Ocorreu uma falha";
                ret.sucesso = false;
            }

            return Json(ret, JsonRequestBehavior.AllowGet);
        }


    }
}

Estabelecimento/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="">
    <title> @ViewBag.Titulo | Controle Estabelecimentos</title>
    <link href="~/Content/css.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/font-awesome-4.7.0/css/font-awesome.css" rel="stylesheet" />
</head>
<body>

    <header>

        <div class="col-md-12 faixa-apresentacao">
            <h1>Sistema de cadastro de estabelecimentos</h1>
        </div>

    </header>

    <aside>
        <!-- sera o menu lateral do sistema -->
        <div class="col-md-2 div-menu">
            <nav>
                <ul id="menu">
                    <li>
                        <a id="home" href="@Url.Action("Index","Home")" onclick="CarregarDinamico('home','0')">Home</a>
                        @*<a href="@Url.Action("Index","Home")">Home</a>*@
                    </li>
                    <li>
                        <a href="#">Estabelecimentos</a>

                        <ul>
                            <li><a id="supermercado" href="#" onclick="CarregarDinamico('supermercado','1')">Supermercado</a></li>
                            @*<li><a href="@Url.Action("Index","Supermercado")">Supermercado</a></li>*@
                            <li><a id="restaurante" href="#" onclick="CarregarDinamico('restaurante','2')">Restaurante</a></li>
                            <li><a id="borracharia" href="#" onclick="CarregarDinamico('borracharia','3')">Borracharia</a></li>
                            <li><a id="posto" href="#" onclick="CarregarDinamico('posto','4')">Posto</a></li>
                            <li><a id="oficina" href="#" onclick="CarregarDinamico('oficina','5')">Oficina</a></li>
                        </ul>

                    </li>
                </ul>
            </nav>

        </div>
    </aside>

    <main>
        <div class="col-md-10">
            @RenderBody()
        </div>
    </main>


    <footer id="footer">
        <div class="col-md-12">

            

            &copy; Leonardo Barbosa 2018
        </div>
    </footer>


    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/carregarTabDinamico.js"></script>
    <script src="~/Scripts/formularioCadastrar.js"></script>
    <script src="~/Scripts/formularioEditar.js"></script>
    <script src="~/Scripts/mascaras.js"></script>
    

</body>
</html>



<script>
    function Visualizar(id_estabelecimento) {
        $('#' + id_estabelecimento).removeClass("disp-none");
    }

    function Fechar(id_estabelecimento) {
        $('#' + id_estabelecimento).addClass("disp-none");
    }

    function Editar(val) {
        $.get('@Url.Action("Editar", "Gerenciador")', 'id=' + val, function (data) {
            $('#exampleModal').find('.modal-title').html("Editar" + "#" + val);
            $('#exampleModal').find('.modal-body').html(data);
            $('#exampleModal').find('.modal-footer').hide();
            $('#exampleModal').modal('show');
        });
    }


</script>

<script>
    function Excluir(id, nomeCat, id_cat) {
        var excluir = confirm("Excluir este estabelecimento?");
        if (excluir == true) {
            
            $.post('@Url.Action("Excluir", "Gerenciador")', 'id_estabelecimento=' + id, function (data) {
                
                CarregarDinamico(nomeCat.toLowerCase(), id_cat);
            });

            console.log(nomeCat.toLowerCase());
            console.log(id_cat);
        }
    }
</script>